create table public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  movement_type text not null,
  quantity integer not null,
  stock_before integer not null,
  stock_after integer not null,
  reference_type text,
  reference_id bigint,
  keterangan text,
  created_by uuid not null,
  created_at timestamptz not null default now(),

  constraint stock_movements_product_id_fkey
    foreign key (product_id)
    references public.products(id),

  constraint stock_movements_created_by_fkey
    foreign key (created_by)
    references public.profiles(id),

  constraint stock_movements_movement_type_check
    check (movement_type in ('IN', 'OUT', 'ADJUSTMENT')),

  constraint stock_movements_quantity_nonzero
    check (quantity <> 0),

  constraint stock_movements_stock_before_nonnegative
    check (stock_before >= 0),

  constraint stock_movements_stock_after_nonnegative
    check (stock_after >= 0)
);

alter table public.stock_movements enable row level security;